wandb_version: 1

Batch size:
  desc: null
  value: 4
Epochs:
  desc: null
  value: 100
LR Scheduler:
  desc: null
  value: CosineAnnealingWarmRestarts
Learning Rate:
  desc: null
  value: 0.01
Loss fn:
  desc: null
  value: Dice
Metric:
  desc: null
  value:
  - IOUscore
  - PixelAccuracy
Optimizer:
  desc: null
  value: SGD
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1673394372.103546
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.9.15
      5: 0.13.5
      8:
      - 1
      - 4
      - 5
